#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "_ksql_server_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_ksql_server_volume"
			result=$(docker volume ls | grep "_ksql_server_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
